name: project-service

services:
  postgres:
    image: postgres:16-alpine
    container_name: ${DB_NAME:-db-lcl}
    environment:
      POSTGRES_DB: ${DB_NAME:-db-lcl}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASS:-admin}
      TZ: UTC

    ports:
      - "${DB_PORT:-5432}:5432"

  member-api-mock:
    image: mockserver/mockserver:5.15.0
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializer.json
    volumes:
      - ./mocks:/config
